language: objective-c
osx_image: xcode9
env:
  global:
    - PROJECT=StringAlgorithms.xcodeproj
    - SCHEME=StringAlgorithms
    - DESTINATION="platform=iOS Simulator,name=iPhone 6,OS=8.1"
script:
  - xcodebuild clean build -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -quiet
  - xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES test -quiet